### PR TITLE
Remove externals from webpack dist configuration

### PR DESCRIPTION
**Pull request by josebailo**
This configuration causes an error resolving Vue instance when building on linux OS.

On Windows OS this error does not occur because of (I think) his non-case sensitive file system.

This makes unnecessary the alias `'Vue$': 'vue/dist/vue.esm.js'` wrote on #11.

### CODE REVIEW

**Comment by mazipan** [comment]
As far as I know if we not include `Externals` it will build with Vue file.
Can you help to check it @josebailo

**Comment by mazipan** [comment]
In this template https://github.com/prograhammer/vue-library-template/blob/master/template/build/webpack.base.conf.js#L26 also set config alias but with
```
'vue$': 'vue/dist/vue.esm.js'
```
can we use this @josebailo ?

**Comment by mazipan** [comment]
So, lets just change alias to 
```
'vue$': 'vue/dist/vue.esm.js'
```
Hope will solve issue

**Comment by mazipan** [comment]
Very thanks for your help ya @josebailo

**Comment by josebailo** [comment]
Just tried the new version, works fine.

Great work!

**Pull request merged**
